# Generated by Django 3.2.19 on 2023-05-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employé',
            name='adresse',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='employé',
            name='email',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='employé',
            name='nbr_taches',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employé',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
