# Generated by Django 3.2.19 on 2023-05-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_auto_20230505_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Siege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='employé',
            name='siege',
            field=models.CharField(max_length=266, null=True),
        ),
    ]
