# Generated by Django 3.2.19 on 2023-05-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0003_auto_20230506_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='employé',
            name='salair',
            field=models.IntegerField(null=True),
        ),
    ]
