# Generated by Django 3.2.19 on 2023-05-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0005_employé_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employé',
            name='adresse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employé',
            name='cin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employé',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employé',
            name='nbr_taches',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employé',
            name='nom',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employé',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employé',
            name='prénom',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employé',
            name='salair',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employé',
            name='siege',
            field=models.CharField(blank=True, max_length=266, null=True),
        ),
        migrations.AlterField(
            model_name='employé',
            name='spécialité',
            field=models.CharField(blank=True, max_length=266, null=True),
        ),
    ]
