# Generated by Django 3.2.19 on 2023-05-06 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_auto_20230505_1946'),
        ('taches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taches',
            name='employé',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employers.employé'),
        ),
    ]
