# Generated by Django 3.2.19 on 2023-05-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taches', '0002_taches_employé'),
    ]

    operations = [
        migrations.AddField(
            model_name='taches',
            name='montant',
            field=models.IntegerField(null=True),
        ),
    ]
