# Generated by Django 3.2.19 on 2023-05-14 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taches', '0003_taches_montant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taches',
            name='montant',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
