# Generated by Django 4.2.1 on 2023-05-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taches', '0004_alter_taches_montant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taches',
            options={'ordering': ['-date_debut']},
        ),
        migrations.AlterField(
            model_name='taches',
            name='etat',
            field=models.CharField(default='started', max_length=266),
        ),
    ]
